inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    enabled: true
    ignore_routes:
        - '/wdt*'
        - '/profiler*'
    ignore_commands:
        - 'doctrine:migrations:migrate'
        - 'd:m:m'
        - 'messenger:stats'
        - importmap:install
        - asset-map:compile
        - 'assets:compile'
        - 'debug:autowiring'
        - 'debug:config'
        - 'debug:container'
        - 'debug:event-dispatcher'
        - 'debug:form'
        - 'debug:router'
        - 'debug:translation'
        - 'debug:twig'
        - 'debug:validator'
        - 'make:auth'
        - 'make:command'
        - 'make:controller'
        - 'make:crud'
        - 'make:docker:database'
        - 'make:entity'
        - 'make:fixtures'
        - 'make:form'
        - 'make:functional-test'
        - 'make:message'
        - 'make:messenger-middleware'
        - 'make:migration'
        - 'make:registration-form'
        - 'make:reset-password'
        - 'make:serializer:encoder'
        - 'make:serializer:normalizer'
        - 'make:subscriber'
        - 'make:test'
        - 'make:twig-extension'
        - 'make:unit-test'
        - 'make:user'
        - 'make:validator'
        - 'make:voter'
        - 'asset-map:compile'
        - 'importmap:install'
        - 'fos:js-routing:dump'
        - 'cache:clear'
