framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sais:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: sais
                    queues:
                        sais: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\ResizeImageMessage: sais
            App\Message\SendWebhookMessage: low
#            App\Message\DownloadImage: sais

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
