framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: async
                    queues:
                        async: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
#            shared:
#                dsn: '%env(SHARED_MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    exchange:
#                        name: shared
#                    queues:
#                        shared: ~
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
            resize:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: resize
                    queues:
                        resize: ~
            download:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: download
                    queues:
                        download: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
#            high:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#            low:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
#            App\Message\SendWebhookMessage: low
            Survos\WorkflowBundle\Message\AsyncTransitionMessage: async
#            Survos\SaisBundle\Message\MediaUploadMessage: shared
#            Survos\SaisBundle\Model\MediaModel: shared

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
