# .symfony.local.yaml
workers:
  # built-in command that builds and watches front-end assets
  # yarn_encore_watch:
  #     cmd: ['yarn', 'encore', 'dev', '--watch']
#  yarn_encore_watch: ~

#   built-in command that starts messenger consumer
  messenger_consume_sais:
       cmd: ['symfony', 'console', 'messenger:consume', 'download']
       watch: ['config', 'src', 'templates', 'vendor']
  messenger_consume_resize:
    cmd: ['symfony', 'console', 'messenger:consume', 'resize']
    watch: ['config', 'src', 'templates', 'vendor']

#  messenger_consume_async: ~

  # you can also add your own custom commands
#  build_spa:
#    cmd: ['yarn', '--cwd', './spa/', 'dev']

