<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250218163637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE key_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX kv_type_value ON key_value (type, value)');
        $this->addSql('CREATE TABLE media (mime_type VARCHAR(16) DEFAULT NULL, size INT DEFAULT NULL, thumb_data JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, blur VARCHAR(255) DEFAULT NULL, root VARCHAR(32) NOT NULL, code VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, original_url TEXT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY(code))');
        $this->addSql('CREATE TABLE thumb (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size INT DEFAULT NULL, w INT DEFAULT NULL, h INT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, liip_code VARCHAR(16) NOT NULL, marking VARCHAR(32) DEFAULT NULL, media_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1537D1DBEA9FDD75 ON thumb (media_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, media_callback_url VARCHAR(255) DEFAULT NULL, thumb_callback_url VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, api_key VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE thumb ADD CONSTRAINT FK_1537D1DBEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (code) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE thumb DROP CONSTRAINT FK_1537D1DBEA9FDD75');
        $this->addSql('DROP TABLE key_value');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE thumb');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
