<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250216110029 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resized (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, liip_code VARCHAR(16) NOT NULL, size INT DEFAULT NULL, w INT DEFAULT NULL, h INT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, media_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4DCD7526EA9FDD75 ON resized (media_id)');
        $this->addSql('ALTER TABLE resized ADD CONSTRAINT FK_4DCD7526EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (code) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media ADD marking VARCHAR(32) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resized DROP CONSTRAINT FK_4DCD7526EA9FDD75');
        $this->addSql('DROP TABLE resized');
        $this->addSql('ALTER TABLE media DROP marking');
    }
}
